security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Public firewall for login
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Secure API routes with JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt:  # This section ensures JWT is used
                authenticator: lexik_jwt_authentication.security.jwt_authenticator

    access_control:
        # Public access for the login route
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # This for access to the API documentation in the browser without JWT authentication
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }

        # Restrict all API routes to authenticated users with JWT
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
